FROM continuumio/miniconda3:latest
WORKDIR /app
COPY 1.sh .
RUN conda install -y python=3.8 mlflow boto3 pymysql
RUN chmod +x 1.sh
CMD ["bash", "-c", "./1.sh && tail -f /dev/null"]
docker build -t netology-ml:netology-ml .
docker run -it --rm netology-ml:netology-ml

